const crawlerSources = [
  {
    key: 'vnexpress-business',
    name: 'VnExpress Kinh doanh',
    siteUrl: 'https://vnexpress.net',
    rssUrl: 'https://vnexpress.net/rss/kinh-doanh.rss',
    category: 'business',
    language: 'vi',
  },
  {
    key: 'cafef-enterprise',
    name: 'CafeF Doanh nghiệp',
    siteUrl: 'https://cafef.vn',
    rssUrl: 'https://cafef.vn/doanh-nghiep.rss',
    category: 'enterprise',
    language: 'vi',
  },
  {
    key: 'cafef-market',
    name: 'CafeF Thị trường chứng khoán',
    siteUrl: 'https://cafef.vn',
    rssUrl: 'https://cafef.vn/thi-truong-chung-khoan.rss',
    category: 'market',
    language: 'vi',
  },
  {
    key: 'cafebiz-business',
    name: 'CafeBiz Kinh doanh',
    siteUrl: 'https://cafebiz.vn',
    rssUrl: 'https://cafebiz.vn/rss/cau-chuyen-kinh-doanh.rss',
    category: 'business',
    language: 'vi',
  },
  {
    key: 'cafebiz-finance',
    name: 'CafeBiz Tài chính ngân hàng',
    siteUrl: 'https://cafebiz.vn',
    rssUrl: 'https://cafebiz.vn/rss/ngan-hang-tai-chinh.rss',
    category: 'finance',
    language: 'vi',
  },
  {
    key: 'cafebiz-stocks',
    name: 'CafeBiz Chứng khoán',
    siteUrl: 'https://cafebiz.vn',
    rssUrl: 'https://cafebiz.vn/rss/chung-khoan.rss',
    category: 'stocks',
    language: 'vi',
  },
  {
    key: 'vietstock-business-operations',
    name: 'Vietstock Hoạt động kinh doanh',
    siteUrl: 'https://vietstock.vn',
    rssUrl: 'http://vietstock.vn/737/doanh-nghiep/hoat-dong-kinh-doanh.rss',
    category: 'business-operations',
    language: 'vi',
  },
  {
    key: 'thanhnien-enterprise',
    name: 'Thanh Niên Doanh nghiệp',
    siteUrl: 'https://thanhnien.vn',
    rssUrl: 'https://thanhnien.vn/rss/kinh-te/doanh-nghiep.rss',
    category: 'enterprise',
    language: 'vi',
  },
  {
    key: 'bnews-enterprise',
    name: 'Bnews Doanh nghiệp',
    siteUrl: 'https://bnews.vn',
    rssUrl: 'https://bnews.vn/rss/doanh-nghiep-6.rss',
    category: 'enterprise',
    language: 'vi',
  },
  {
    key: 'bnews-enterprise-moves',
    name: 'Bnews Chuyển động DN',
    siteUrl: 'https://bnews.vn',
    rssUrl: 'https://bnews.vn/rss/chuyen-dong-dn-24.rss',
    category: 'enterprise-moves',
    language: 'vi',
  },
  {
    key: 'bnews-enterprise-analysis',
    name: 'Bnews Phân tích doanh nghiệp',
    siteUrl: 'https://bnews.vn',
    rssUrl: 'https://bnews.vn/rss/phan-tich-doanh-nghiep-41.rss',
    category: 'enterprise-analysis',
    language: 'vi',
  },
  {
    key: 'baodautu-business',
    name: 'Báo Đầu Tư Kinh doanh',
    siteUrl: 'https://baodautu.vn',
    rssUrl: 'https://baodautu.vn/kinh-doanh.rss',
    fallbackListingUrl: 'https://baodautu.vn/tag/kinh-doanh/',
    category: 'business',
    language: 'vi',
  },
  {
    key: 'baodautu-businessman',
    name: 'Báo Đầu Tư Doanh nhân',
    siteUrl: 'https://baodautu.vn',
    rssUrl: 'https://baodautu.vn/doanh-nhan.rss',
    fallbackListingUrl: 'https://baodautu.vn/tag/doanh-nhan/',
    category: 'businessman',
    language: 'vi',
  },
]

module.exports = crawlerSources
