module.exports = [
  {
    key: 'bao-tin-minh-chau',
    name: 'Bảo Tín Minh Châu',
    industry: 'Jewelry',
    ticker: null,
    aliases: ['bảo tín minh châu', 'bao tin minh chau'],
  },
  {
    key: 'traphaco',
    name: 'Traphaco',
    industry: 'Healthcare',
    ticker: 'TRA',
    aliases: ['traphaco'],
  },
  {
    key: 'f88',
    name: 'F88',
    industry: 'Financial Services',
    ticker: null,
    aliases: ['f88'],
  },
  {
    key: 'fecon',
    name: 'Fecon',
    industry: 'Construction',
    ticker: 'FCN',
    aliases: ['fecon'],
  },
  {
    key: 'dat-xanh-services',
    name: 'Đất Xanh Services',
    industry: 'Real Estate',
    ticker: 'DXS',
    aliases: ['đất xanh services', 'dat xanh services', 'dxs'],
  },
  {
    key: 'viettel-construction',
    name: 'Viettel Construction',
    industry: 'Infrastructure',
    ticker: 'CTR',
    aliases: ['viettel construction'],
  },
  {
    key: 'pvoil',
    name: 'PVOIL',
    industry: 'Energy',
    ticker: 'OIL',
    aliases: ['pvoil', 'oil', 'tổng công ty dầu việt nam'],
  },
  {
    key: 'rox-energy',
    name: 'ROX Energy',
    industry: 'Energy',
    ticker: null,
    aliases: ['rox energy', 'rox group'],
  },
  {
    key: 'phu-tai',
    name: 'Phú Tài',
    industry: 'Materials',
    ticker: 'PTB',
    aliases: ['phú tài', 'phu tai', 'ptb'],
  },
  {
    key: 'vissan',
    name: 'Vissan',
    industry: 'Consumer Goods',
    ticker: 'VSN',
    aliases: ['vissan', 'vsn'],
  },
  {
    key: 'tco-holdings',
    name: 'TCO Holdings',
    industry: 'Agriculture',
    ticker: 'TCO',
    aliases: ['tco holdings', 'tco'],
  },
  {
    key: 'superdong-kien-giang',
    name: 'Superdong Kiên Giang',
    industry: 'Transportation',
    ticker: 'SKG',
    aliases: ['superdong', 'superdong kiên giang', 'superdong kien giang', 'skg'],
  },
]
